### PR TITLE
Aktualisierung

### PR DESCRIPTION
**Pull request by nagy**

### CODE REVIEW

**Comment by nagy** [comment]
I have updated this PR to the most recent dataset.

**Comment by mk-pmb** [comment]
Thanks for your help! Unfortunately this repo seems rather dead since 2013, see #55. I'm one of the maintainers but I don't know how to verify your contribution. Maybe someone of the others knows.

**Comment by ulfgebhardt** [comment]
We just merge and hope for the best.
@nagy Since you managed to generate the data with the generator tool, would you be willing to make this a workflow on github to do that every night?

**Comment by nagy** [comment]
What I did was just to rerun the tooling and commit everything that changed in one, and without a proper message attached to it.

The initial idea behind this repository was that all actual updates to laws should have git commits that reflect this change. This requires proper changesets and proper commits message with reference links to official sources of these law changes.

I already talked a bit with @stefanw about building such changesets and I think it would be best to continue this discussion in the https://github.com/bundestag/gesetze-tools repository.

> Since you managed to generate the data with the generator tool, would you be willing to make this a workflow on github to do that every night?

Only reluctantly because this github workflow would only be of short temporal use. It would be better to invest the time into implementing the logic I mentioned before.

However, I would agree, that some dumps are better than none at all. What I can offer is that I can make manual periodic dumps until we are done with the proper implementation of it. Would this be welcomed?

**Pull request merged**
